/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test1_Test1 */

#ifndef _Included_test1_Test1
#define _Included_test1_Test1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test1_Test1
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_test1_Test1_multiply
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
